TYPE=tarball-repackage
BASE_VERSION=1.20.1b
REPO=zen-browser/desktop
BRANCH=main
TARBALL_URL=https://github.com/zen-browser/desktop/releases/download/${VERSION}/zen.linux-x86_64.tar.xz
LICENSE_URL=https://raw.githubusercontent.com/zen-browser/desktop/refs/heads/dev/LICENSE
