TYPE=deb-repackage
BASE_VERSION=2.22.0
REPO=Heroic-Games-Launcher/HeroicGamesLauncher
BRANCH=main
DEB_URL=https://github.com/Heroic-Games-Launcher/HeroicGamesLauncher/releases/download/v${VERSION}/Heroic-${VERSION}-linux-amd64.deb
